apiVersion: v1
kind: Service
metadata:
  name: node-{{ include "omicsdi.fullname" . }}
  labels:
{{ include "omicsdi.labels" . | indent 4 }}
spec:
  type: {{ .Values.nodeservice.type }}
  ports:
    - port: {{ .Values.nodeservice.port }}
      name: http
  selector:
    app.kubernetes.io/name: {{ include "omicsdi.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
