apiVersion: v1
kind: Service
metadata:
  name: node-{{ include "omicsfront.fullname" . }}
  labels:
{{ include "omicsfront.labels" . | indent 4 }}
spec:
  type: {{ .Values.nodeservice.type }}
  ports:
    - port: {{ .Values.nodeservice.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "omicsfront.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
