apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ssr.servicename }}
  labels:
{{ include "omicsfront.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.ssr.port }}
      targetPort: {{ .Values.ssr.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "omicsfront.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
